### ISSUE TITLE
create new API endpoint for enrichment (related to #12)

### ISSUE THREAD

**Issue by mlodic** [honeynet/GreedyBear#17]
related to #12

**Comment by uzaxirr** [comment]
Hey please assign this to me so that i can start working on this

**Comment by uzaxirr** [comment]
@mlodic 
Can you please document the steps to set up the project locally.
I tried installing requirements.txt but received a huge error log

**Comment by mlodic** [comment]
well the technologies and the set up is almost the same of IntelOwl, except that we do not have an helper script.py so you need to use `docker-compose` commands directly. For now, I have just pushed the commands in the `develop` branch [here](https://github.com/honeynet/GreedyBear/tree/develop#how-to-execute-it-locally-for-testing). I will move them into the official documentation soon

**Comment by uzaxirr** [comment]
@mlodic This can be closed now as #25 resolves this
