### ISSUE TITLE
Adding basic test suite

### ISSUE THREAD

**Issue by mlodic** [honeynet/GreedyBear#21]
We should properly mock the query to ElasticSearch to have the tests work in Github Actions. Please refer to [IntelOwl](https://github.com/intelowlproject/IntelOwl) to get an example

**Comment by uzaxirr** [comment]
Could you enlighten me on the purpose of files currently present in `tests/greedybear/cronjobs`
I guess i just have to add a `__init__.py` file in the currently present `tests` directory to convert it into a module and add test for CRUD methods on existing models and test the API endpoints.

or do i have to make utils for APIView

Please correct me if i'm wrong in any of the above

**Comment by mlodic** [comment]
well, actually there are not tests enabled in the CI (see pull_request_automation.yml).

As you mentioned, in that folder there are some tests but:
* they only work if manually launched because they require to have an ElasticSearch instance with the right data active and connected. This is why I asked to mock ElasticSearch connections (fake them and have them return fake data so the code would correctly execute until its end) to have the tests working even in the Github CI.
* those tests are only for the cronjobs part (interaction with ElasticSearch). As you mentioned, there are no tests for the API endpoints and we should add them (something very similar to the tests for the APIs in IntelOwl)

**Comment by uzaxirr** [comment]
Cool seems fine, can you assign it to me as my current PR is under-review from a long time so would work on this one parallelly.

**Comment by mlodic** [comment]
dolved in #38
