### ISSUE TITLE
Elasticsearch installation error

### ISSUE THREAD

**Issue by uzaxirr** [honeynet/GreedyBear#23]
i'm encountering some error while setting up GreedyBear locally
After doing the `docker-compose -p greedybear up` cmd.
It originates from settings.py where Elasticsearch client is being initialized. The ELASTIC_ENDPOINT variable in my env file is empty
![Screenshot from 2022-01-02 19-51-22](https://user-images.githubusercontent.com/72073401/147880136-9c712db0-3f63-481d-91bb-cc4f63aa5921.png)

**Comment by mlodic** [comment]
- [ ] we can just make a conditional statement in the settings.py that if that value is empty the application just do not run and exit with an error

- [x] we could add an elasticsearch container that should be used only for development (local.yml) and connect the application to it. In this way, it is also possible to perform some manual tests with a working ElasticSearch instance.

**Comment by mlodic** [comment]
other inputs here https://github.com/intelowlproject/IntelOwl/issues/808

**Comment by devmrfitz** [comment]
@mlodic I'd like to work on this issue

**Comment by mlodic** [comment]
solved in #30
