### ISSUE TITLE
use DRF for views and django-rest-durin for authentication

### ISSUE THREAD

**Issue by eshaan7** [honeynet/GreedyBear#26]
Approved by @mlodic.

Use how these packages are integrated in IntelOwl for reference.

**Comment by yaswanthsaivendra** [comment]
can I work on this issue?

**Comment by ManishShah120** [comment]
Hi, @eshaan7 Can I please work on this, I want to learn more about this project, and make some useful patches in the coming future.

--Thank You 😄

**Comment by ManishShah120** [comment]
Thanx for assigning. On it

**Comment by uzaxirr** [comment]
@ManishShah120 you still working on this?

**Comment by mlodic** [comment]
A week has passed, I am removing the assignment tomorrow 

See: https://intelowl.readthedocs.io/en/latest/Contribute.html

**Comment by ManishShah120** [comment]
Okay, @mlodic I won't be able to open a PR, by tomorrow.

> @ManishShah120 you still working on this?

I was trying to get started with it, but it seems it is taking too long for me. I am unassigning myself.

**Comment by uzaxirr** [comment]
@mlodic 
By "Use DRF for Views" i assume you mean to convert the existing `feeds` view to a DRF based view and add authentication in the APIs correct?
is there anything i'm missing?

**Comment by mlodic** [comment]
yeah, but remember that you still have an open PR to finish before taking up such an issue

**Comment by Yshaq** [comment]
Hey, can I pick up this issue?

**Comment by uzaxirr** [comment]
Hey, Can I work on this now

**Comment by uzaxirr** [comment]
Hey I've done the Converting views to DRF views part. Just to make sure that we are on same page regarding Rest-Durin i wanna confirm that you want to add configurations for Durin and Create the following endpoints
- `/api/auth/login`
- `/api/auth/logout`
- `/api/auth/logoutall`
- `/api/auth/sessions`
- `/api/auth/apiaccess`
Am i correct or missing something?

In IntelOwl i see only `/api/auth/login` and `/api/auth/logout`

**Comment by mlodic** [comment]
please refer to the branch `dev-v4` there: https://github.com/intelowlproject/IntelOwl/tree/dev-v4/api_app/auth

**Comment by mlodic** [comment]
closing this issue for now cause solved with simple TokenAuthentication
