### ISSUE TITLE
Add DRF Throttling for AnonUsers

### ISSUE THREAD

**Issue by mlodic** [honeynet/GreedyBear#31]
This is to protect admin/APIs from abuse

See: https://www.django-rest-framework.org/api-guide/throttling/#api-reference

**Comment by eshaan7** [comment]
Use https://github.com/intelowlproject/IntelOwl/issues/884 thread for discussions on this.

**Comment by devmrfitz** [comment]
For this, we use the nginx approach for the admin panel and the DRF's inbuilt approach for the DRF views. Is that correct, @mlodic @eshaan7 ?

**Comment by devmrfitz** [comment]
The rate is supposed to be 1 req/s in both cases?

**Comment by mlodic** [comment]
I'd same same as IntelOwl

**Comment by devmrfitz** [comment]
> I'd same same as IntelOwl

Just for verification, even DRF views should be rate-limited using nginx?
@mlodic

**Comment by mlodic** [comment]
admins + the anauthenticated APIs (the only one that exist is the feeds one)

**Comment by devmrfitz** [comment]
But what if an authenticated user wants to access the feeds API? They would get rate-limited too

**Comment by mlodic** [comment]
Yeah but that would make sense too in my opinion.

**Comment by mlodic** [comment]
I mean, right now we have no quotas implemented for the authenticated users. Once we will have that, we could change it.

**Comment by devmrfitz** [comment]
Alright

**Comment by 0x0elliot** [comment]
Hey, If no one is working on it can I take over this one? Seems like a simple enough issue to help out with.

**Comment by 0x0elliot** [comment]
@devmrfitz i hope you are not already taking care of this and would be fine with it?

**Comment by devmrfitz** [comment]
Hello @0x0elliot 
I'd already made a commit [2dbfaa1](https://github.com/devmrfitz/GreedyBear/commit/2dbfaa16b117331e0db6787c14e059d1d7f7aaaa) yesterday but forgot to make a PR for the same. Will do it now

**Comment by 0x0elliot** [comment]
thanks for letting me know @devmrfitz! Is there anything I can help you out with for this issue?

**Comment by devmrfitz** [comment]
@mlodic Additionally, the PR template asks us to verify that our PR is for the `dev` branch, but there is no such branch on `honeynet/GreedyBear`

**Comment by devmrfitz** [comment]
> thanks for letting me know @devmrfitz! Is there anything I can help you out with for this issue?

I think @mlodic will be the better person to answer that. However, if there's an issue with my PR, you might be able to work on it (as per mlodic's instructions).

**Comment by 0x0elliot** [comment]
> I think @mlodic will be the better person to answer that. However, if there's an issue with my PR, you might be able to work on it (as per mlodic's instructions).

Pretty sure he would get back to us by Monday. Till then, what exactly is the issue? I might be able to help out with it.

**Comment by mlodic** [comment]
done in #40
