### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ManishShah120** [honeynet/GreedyBear#37]
Can we please add or refer to the URL containing the guidelines for future contributors, I see there's nothing mentioned about it in the readme or docs for this repo.

**Comment by mlodic** [comment]
Yeah, the project is quite new and we need to create proper documentation (see open issue #27 ).

Meanwhile, it would be enough to follow the generic rules stated for another project handled by us, IntelOwl. See https://intelowl.readthedocs.io/en/latest/Contribute.html

**Comment by mlodic** [comment]
added in `develop` branch
